nginx:
  service:
    ports:
      http: 80
    nodePorts:
      http: 30026
    type: <#if isRemote>LoadBalancer<#else>NodePort</#if>
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 30m
      memory: 15Mi

<#if exampleApps.nginx.baseDomain?has_content>
  ingress:
    enabled: true
    pathType: Prefix
    <#if urlSeparatorHyphen>
    hostname: production-nginx-helm-umbrella-${exampleApps.nginx.baseDomain}
    <#else>
    hostname: production.nginx-helm-umbrella.${exampleApps.nginx.baseDomain}
    </#if>
</#if>
