# this misc-Application manages all resources in the misc folder in the gitops repository
# use the misc folder to deploy resources, which are needed for multiple other apps such as ServiceAccounts or shared ConfigMaps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <#if config.multiTenant.useDedicatedInstance>${config.application.namePrefix}misc<#else>misc</#if>
  namespace: <#if config.multiTenant.useDedicatedInstance>${config.multiTenant.centralArgocdNamespace}<#else>${config.application.namePrefix}argocd</#if>
spec:
  project: <#if config.multiTenant.useDedicatedInstance>${tenantName}<#else>cluster-resources</#if>
  destination:
    server: https://kubernetes.default.svc
    namespace: <#if config.multiTenant.useDedicatedInstance>${config.multiTenant.centralArgocdNamespace}<#else>${config.application.namePrefix}argocd</#if>
  source:
    path: misc/
<#if config.multiTenant.useDedicatedInstance>
    repoURL: ${scm.centralScmUrl}argocd/cluster-resources.git
<#else>
    repoURL: ${scm.repoUrl}argocd/cluster-resources.git
</#if>
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true