apiVersion: v1
kind: Namespace
metadata:
  name: ${namePrefix}example-apps-staging
  labels:
    name: ${namePrefix}example-apps-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${namePrefix}example-apps-production
  labels:
    name: ${namePrefix}example-apps-production
---
