<#if !config.application.openshift && !config.application.namespaceIsolation>
apiVersion: v1
kind: Namespace
metadata:
  name: ${namePrefix}example-apps-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${namePrefix}example-apps-production
---
</#if>