<#assign DockerImageParser=statics['com.cloudogu.gitops.utils.DockerImageParser']>
ui: 
  enabled: true
  externalPort: 80
<#if config.application.remote>
  serviceType: "LoadBalancer"
<#else>
  serviceType: NodePort
  serviceNodePort: 8200
</#if>
injector: 
  enabled: false
<#if config.registry.createImagePullSecrets?has_content && config.registry.twoRegistries?has_content>
global:
  imagePullSecrets:
  - name: proxy-registry
</#if>
<#if config.features.secrets.vault.helm.image?has_content 
  || url?has_content 
  || config.application.podResources == true>
server:
</#if>
<#if config.features.secrets.vault.helm.image?has_content>
<#assign imageObject = DockerImageParser.parse(config.features.secrets.vault.helm.image)>
  image:
      repository: ${imageObject.registryAndRepositoryAsString}
      tag: ${imageObject.tag}
</#if>
<#if url?has_content>
  ingress:
    enabled: true
    hosts:
      - host: ${url.host}
</#if>

<#if config.application.podResources == true>
  resources:
      limits:
        memory: 200Mi
        cpu: 500m
      requests:
        memory: 100Mi
        cpu: 50m
</#if>