service:
  port: 80

<#if config.features.exampleApps.petclinic.baseDomain?has_content>
ingress:
  hosts:
    <#if config.application.urlSeparatorHyphen>
    - host: production-petclinic-helm-${config.features.exampleApps.petclinic.baseDomain}
    <#else>
    - host: production.petclinic-helm.${config.features.exampleApps.petclinic.baseDomain}
    </#if>
      paths: ['/']
</#if>
