service:
  port: 80
  nodePort: 30022

<#if exampleApps.petclinic.baseDomain?has_content>
ingress:
  hosts:
    <#if urlSeparatorHyphen>
    - host: staging-petclinic-helm-${exampleApps.petclinic.baseDomain}
    <#else>
    - host: staging.petclinic-helm.${exampleApps.petclinic.baseDomain}
    </#if>
      paths: ['/']
</#if>
