apiVersion: rbac.authorization.k8s.io/v1
kind: ${kind}
metadata:
  name: ${name}
  namespace: ${namespace}
subjects:
  <#list serviceAccounts as sa>
  - kind: ServiceAccount
    name: ${sa.name}
    namespace: ${sa.namespace}
  </#list>
roleRef:
  kind: ${roleKind}
  name: ${roleName}
  apiGroup: rbac.authorization.k8s.io
