extraEnv: |
  - name: TZ
    value: Europe/Berlin
service:
  type: <#if isRemote>LoadBalancer<#else>NodePort</#if>

ingress:
  enabled: <#if exampleApps.petclinic.baseDomain?has_content>true<#else>false</#if>

# this is a helm chart dependency
podinfo:
  ui:
    color: '#456456'

  <#if podResources == true>
resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 650Mi
  <#else>
  <#-- Explicitly set to null, because the chart sets memory by default
  https://github.com/cloudogu/spring-boot-helm-chart/blob/0.3.2/values.yaml#L40 -->
resources: null
  </#if>