apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "${namePrefix}example-apps-staging"
  name: argocd
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - persistentvolumeclaims
      - services
      - serviceaccounts
      - pods
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
    verbs:
      - list
      - watch
      - get
      - create
      - update
      - delete 
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "argoproj.io"
    resources:
      - applicationsets
      - applications
      - appprojects
      - argocds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "external-secrets.io"
    resources:
      - secretstores
      - externalsecrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - alertmanagers
      - alertmanagers/finalizers
      - alertmanagerconfigs
      - prometheuses
      - prometheuses/status
      - prometheuses/finalizers
      - prometheusrules
      - thanosrulers
      - thanosrulers/status
      - thanosrulers/finalizers
      - servicemonitors
      - podmonitors
      - probes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd
  namespace: "${namePrefix}example-apps-staging"
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-server
    namespace: "${namePrefix}argocd"
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: "${namePrefix}argocd"
  - kind: ServiceAccount
    name: argocd-applicationset-controller
    namespace: "${namePrefix}argocd"
roleRef:
  kind: Role
  name: argocd
  apiGroup: rbac.authorization.k8s.io