# $schema: https://raw.githubusercontent.com/cloudogu/gitops-playground/main/docs/configuration.schema.json
application:
  "yes": true
  baseUrl: http://localhost
  insecure: true
  namePrefix: my-prefix
features:
  argocd:
    active: true
  ingress:
    active: true

content:
  helmReleases:
    - name: elasticsearch
      repoURL: https://helm.elastic.co
      chart: elasticsearch
      version: "8.5.1"
      namespace: my-prefix-elasticsearch
      valuesFrom:
        - repoURL: https://github.com/cloudogu/gitops-playground
          ref: feature/helm_by_content_loader
          path: src/main/resources/elasticsearch-helm.yaml

registry:
  active: true