# $schema: https://raw.githubusercontent.com/cloudogu/gitops-playground/main/docs/configuration.schema.json
application:
  "yes": true
  baseUrl: http://localhost
  insecure: true
  namePrefix: my-prefix
features:
  argocd:
    active: true
    operator: false
  ingress:
    active: true

content:
  helmReleases:
    - name: harbor
      repoURL: https://helm.goharbor.io
      chart: harbor
      version: "1.18.2"
      namespace: my-prefix-harbor
      releaseName: harbor
      values:
        expose:
          type: ingress
          tls:
            enabled: false
          ingress:
            className: traefik
            hosts:
              core: core.harbor.domain
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
              traefik.ingress.kubernetes.io/router.tls: "false"

        externalURL: http://core.harbor.domain

        harborAdminPassword: "Harbor12345"
        secretKey: "change-me-please-16chars"

registry:
  active: true