# $schema: https://raw.githubusercontent.com/cloudogu/gitops-playground/main/docs/configuration.schema.json
application:
  "yes": true
  baseUrl: http://localhost
features:
  certManager:
    active: true
  argocd:
    active: true
    operator: false
  ingress:
    active: true
  monitoring:
    active: true
  secrets:
    vault:
      mode: "dev"
jenkins:
  active: true
registry:
  active: true
content:
  repos:
    - url: https://github.com/cloudogu/gitops-build-lib
      target: 3rd-party-dependencies/gitops-build-lib
      overwriteMode: RESET
    - url: https://github.com/cloudogu/ces-build-lib
      target: 3rd-party-dependencies/ces-build-lib
      overwriteMode: RESET
    - url: https://github.com/cloudogu/spring-boot-helm-chart
      target: 3rd-party-dependencies/spring-boot-helm-chart
      overwriteMode: RESET
    - url: https://github.com/cloudogu/spring-petclinic
      target: argocd/petclinic-plain
      ref: feature/gitops_ready
      targetRef: main
      overwriteMode: UPGRADE
      createJenkinsJob: true
    - url: https://github.com/cloudogu/spring-petclinic
      target: argocd/petclinic-helm
      ref: feature/gitops_ready
      targetRef: main
      overwriteMode: UPGRADE
      createJenkinsJob: true
    - url: https://github.com/cloudogu/gitops-examples
      path: example-apps-via-content-loader/
      ref: main
      templating: true
      type: FOLDER_BASED
      overwriteMode: UPGRADE

  namespaces:
    - ${config.application.namePrefix}example-apps-production
    - ${config.application.namePrefix}example-apps-staging
  variables:
    petclinic:
      baseDomain: "petclinic.localhost"
    images:
      kubectl: "alpine/kubectl:1.35.4"
      helm: "ghcr.io/cloudogu/helm:3.16.4-1"
      kubeval: "ghcr.io/cloudogu/helm:3.16.4-1"
      helmKubeval: "ghcr.io/cloudogu/helm:3.16.4-1"
      yamllint: "cytopia/yamllint:1.25-0.7"
      petclinic: "eclipse-temurin:17-jre-alpine"
      maven: ""
