# this misc-Application manages all resources in the misc folder in the gitops repository
# use the misc folder to deploy resources, which are needed for multiple other apps such as ServiceAccounts or shared ConfigMaps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<#if argocd.isOperator>
  name: misc-example-apps-production
  namespace: ${namePrefix}argocd
<#else>
  name: misc
  namespace: ${namePrefix}example-apps-production
</#if>
spec:
  project: example-apps
  destination:
    server: https://kubernetes.default.svc
    # a namespace must be specified here, because teams are not allowed to deploy cluster-wide.
    # You can specify a different namespace in the ressource YAMLs, if you are permitted to deploy in them
    namespace: ${namePrefix}example-apps-production
  source:
    path: misc/
    repoURL: ${scmm.repoUrl}argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
<#if config.multiTenant.centralSCMUrl?has_content>
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example-apps
  namespace: ${namePrefix}argocd
spec:
  description: Contains examples of end-user application
  destinations:
    - namespace: ${namePrefix}example-apps-production
      server: https://kubernetes.default.svc
    - namespace: ${namePrefix}example-apps-staging
      server: https://kubernetes.default.svc
    - namespace: ${namePrefix}argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - http://scmm.${namePrefix}scm-manager.svc.cluster.local/scm/repo/${namePrefix}argocd/example-apps
    - http://scmm.${namePrefix}scm-manager.svc.cluster.local/scm/repo/${namePrefix}argocd/nginx-helm-umbrella

  sourceNamespaces:
    - ${namePrefix}example-apps-staging
    - ${namePrefix}example-apps-production
    - ${namePrefix}argocd

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  clusterResourceWhitelist: []
</#if>