# this misc-Application manages all resources in the misc folder in the gitops repository
# use the misc folder to deploy resources, which are needed for multiple other apps such as ServiceAccounts or shared ConfigMaps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc
  namespace: argocd-production
spec:
  project: example-apps
  destination:
    server: https://kubernetes.default.svc
    # a namespace must be specified here, because teams are not allowed to deploy cluster-wide.
    # You can specify a different namespace in the ressource YAMLs, if you are permitted to deploy in them
    namespace: argocd-production
  source:
    path: misc/
    repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true