apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<#if argocd.isOperator>
  name: nginx-helm-jenkins-staging
  namespace: ${config.application.namePrefix}argocd
<#else>
  name: nginx-helm-jenkins
  namespace: ${config.application.namePrefix}example-apps-staging
</#if>
spec:
  destination:
    namespace: ${config.application.namePrefix}example-apps-staging
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/nginx-helm-jenkins/staging
    repoURL: ${scmm.repoUrl}argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<#if argocd.isOperator>
  name: nginx-helm-jenkins-production
  namespace: ${config.application.namePrefix}argocd
<#else>
  name: nginx-helm-jenkins
  namespace: ${config.application.namePrefix}example-apps-production
</#if>
spec:
  destination:
    namespace: ${config.application.namePrefix}example-apps-production
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/nginx-helm-jenkins/production
    repoURL: ${scmm.repoUrl}argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true