apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-umbrella
<#if argocd.isOperator>
  namespace: ${namePrefix}argocd
<#else>
  namespace: ${namePrefix}example-apps-production
</#if>
spec:
  destination:
    namespace: ${namePrefix}example-apps-production
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/nginx-helm-umbrella
    repoURL: ${scmm.repoUrl}argocd/example-apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true