apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<#if config.features.argocd.operator>
  name: petclinic-plain-staging
  namespace: ${config.application.namePrefix}argocd
<#else>
  name: petclinic-plain
  namespace: ${config.application.namePrefix}example-apps-staging
</#if>
spec:
  destination:
    namespace: ${config.application.namePrefix}example-apps-staging
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/spring-petclinic-plain/staging
    repoURL: ${scmm.repoUrl}argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<#if config.features.argocd.operator>
  name: petclinic-plain-production
  namespace: ${config.application.namePrefix}argocd
<#else>
  name: petclinic-plain
  namespace: ${config.application.namePrefix}example-apps-production
</#if>
spec:
  destination:
    namespace: ${config.application.namePrefix}example-apps-production
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/spring-petclinic-plain/production
    repoURL: ${scmm.repoUrl}argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true