@startuml

!includeurl https://raw.githubusercontent.com/michiel/plantuml-kubernetes-sprites/master/resource/k8s-sprites-unlabeled-full.iuml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/docker.puml
!includeurl ICONURL/devicons/git.puml
!includeurl ICONURL/font-awesome-5/jenkins.puml
!includeurl ICONURL/font-awesome-5/sync.puml
!includeurl ICONURL/font-awesome-5/box.puml
!includeurl ICONURL/material/computer.puml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/tools/k8s.puml
!includeurl CLOUDOGUURL/dogus/scm.puml

!define CLOUDOGU_BLUE #23a3dd

cloud "Your cloud provider" {

    rectangle "<$k8s>\nk8s Cluster" as k8s {
        
            
        node "Node" as k8sNode <<$computer>> #ffffff {
            rectangle "<$k8s>\nkubelet" as kubelet 
            rectangle "<$docker>\nDocker Daemon" as docker
        }
        
        together {
            rectangle "<$box>\nOCI Registry" as registry
            rectangle "<$scm>\nSCM-Manager" as scmm {
                rectangle "<$git>\nApp Repo" as appRepo
                rectangle "<$git>\nGitOps Repo" as configRepo
            }
        }
        
        rectangle "<$jenkins>\nJenkins Controller" as jenkins
        rectangle "<$jenkins>\nAgent Pods" as jenkinsNode
        
        rectangle "<$sync>\nGitOps-Operator" as gitops
        rectangle "<$k8s>\nAPI-Server" as apiServer
    }
}

appRepo -[hidden]> configRepo
appRepo <-- jenkinsNode : pull
configRepo <-- jenkinsNode : push
registry <-- jenkinsNode : push

kubelet --> apiServer : watch
'docker -[hidden]> apiServer

kubelet --> docker : run containers
jenkins -> jenkinsNode : manage
jenkinsNode -> docker: run containers\nbuild images
gitops --> configRepo : pull
gitops -> apiServer : apply resources

registry <- docker : pull

skinparam arrow {
  Color BLACK
}

skinparam node {
  BorderColor CLOUDOGU_BLUE
}

skinparam actor {
  BackgroundColor #23a3dd
  BorderColor #16688d
  FontColor #000000
}

skinparam actor {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
}

skinparam rectangle {
    BackgroundColor WHITE
    BorderColor CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

skinparam interface {
    BackgroundColor WHITE
    BorderColor #16688d
}

skinparam note {
    BackgroundColor WHITE
    BorderColor #16688d
}

@enduml