<#if nginxImage??>
image:
  registry: ${nginxImage.registry}
  repository: ${nginxImage.repository}
  tag: ${nginxImage.tag}
</#if>
service:
  ports:
    http: 80

staticSiteConfigmap: exercise-index-nginx

extraEnvVars:
  - name: LOG_LEVEL
      value: debug
serverBlock: |-
  server {
    listen 0.0.0.0:8080;
    location /hi {
      return 200 "hello!";
    }
  }

resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 30m
    memory: 15Mi
