namespaceOverride: config.application.namePrefix.example-apps-staging

<#if exampleApps.nginx.baseDomain?has_content>
ingress:
  enabled: true
  pathType: Prefix
  <#if urlSeparatorHyphen>
  hostname: staging-exercise-nginx-helm-${exampleApps.nginx.baseDomain}
  <#else>
  hostname: staging.exercise-nginx-helm.${exampleApps.nginx.baseDomain}
  </#if>
</#if>
