<#assign DockerImageParser=statics['com.cloudogu.gitops.utils.DockerImageParser']>
<#if config.images.nginx?has_content>
<#assign nginxImageObject = DockerImageParser.parse(config.images.nginx)>
image:
  registry: ${nginxImageObject.registry}
  repository: ${nginxImageObject.repository}
  tag: ${nginxImageObject.tag}
</#if>
<#if config.registry.createImagePullSecrets == true>
global:
  imagePullSecrets:
    - proxy-registry
</#if>
service:
  ports:
    http: 80

staticSiteConfigmap: exercise-index-nginx

extraEnvVars:
  - name: LOG_LEVEL
      value: debug
serverBlock: |-
  server {
    listen 0.0.0.0:8080;
    location /hi {
      return 200 "hello!";
    }
  }

<#if config.application.podResources == true>
resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 30m
    memory: 15Mi

</#if>