namespaceOverride: config.application.namePrefix.example-apps-production

<#if exampleApps.nginx.baseDomain?has_content>
ingress:
  enabled: true
  pathType: Prefix
  <#if urlSeparatorHyphen>
  hostname: production-exercise-nginx-helm-${exampleApps.nginx.baseDomain}
  <#else>
  hostname: production.exercise-nginx-helm.${exampleApps.nginx.baseDomain}
  </#if>
</#if>
