namespaceOverride: ${config.application.namePrefix}example-apps-staging

<#if config.features.exampleApps.nginx.baseDomain?has_content>
ingress:
  enabled: true
  pathType: Prefix
  <#if config.application.urlSeparatorHyphen>
  hostname: staging-exercise-nginx-helm-${config.features.exampleApps.nginx.baseDomain}
  <#else>
  hostname: staging.exercise-nginx-helm.${config.features.exampleApps.nginx.baseDomain}
  </#if>
</#if>
