apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-plain
  labels:
    app: spring-petclinic-plain
spec:
  type: <#if config.application.remote>LoadBalancer<#else>NodePort</#if>
  ports:
    - name: http
      port: 80
      nodePort: 30020
      targetPort: http
  selector:
    app: spring-petclinic-plain
