apiVersion: v2
name: ingress-nginx
version: 1.0.0
description: Wraps the upstream ingress-nginx helm chart
dependencies:
  - name: ingress-nginx
    version: 4.8.0
    repository: https://kubernetes.github.io/ingress-nginx