apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: ${namePrefix}argocd
  annotations:
    # Only app with the sync-status-unknown alert, so that we only get one alert when SCM is not reachable.
    # Otherwise, there would be a spam wave by every application everytime the SCM is not reachable.
<#if mail.active?? && mail.active>
    notifications.argoproj.io/subscribe.on-sync-status-unknown.email: ${argocd.emailToAdmin}
</#if>
# finalizer disabled, because otherwise everything under this Application would be deleted as well, if this Application is deleted by accident
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namePrefix}argocd
  project: argocd
  source:
    path: ${argocd.isOperator?string("operator/", "argocd/")}
    repoURL: ${scmm.repoUrl}argocd/argocd<#if scmm.provider == "gitlab">.git</#if>
    targetRevision: main
    # needed to sync the operator/rbac folder
    <#if argocd.isOperator??>
    directory:
      recurse: true
    </#if>
  syncPolicy:
    automated:
      prune: false # is set to false to prevent argo from deleting itself
      selfHeal: true
