apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: ${namePrefix}argocd
# finalizer disabled, because otherwise everything under this Application would be deleted as well, if this Application is deleted by accident
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namePrefix}argocd
  project: argocd
  source:
    path: projects/
    repoURL: ${scmm.baseUrl}/repo/${namePrefix}argocd/argocd
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: false # is set to false to prevent projects to be deleted by accident
      selfHeal: true
