installCRDs: true

resources:
  limits:
    memory: 80Mi
    cpu: 500m
  requests:
    memory: 40Mi
    cpu: 50m

certController:
  resources:
    limits:
      memory: 110Mi
      cpu: 500m
    requests:
      memory: 55Mi
      cpu: 50m

webhook:
  resources:
    limits:
      memory: 50Mi
      cpu: 500m
    requests:
      memory: 25Mi
      cpu: 50m
