installCRDs: true

<#if podResources == true>
certController:
  resources:
    limits:
      memory: 110Mi
      cpu: 500m
    requests:
      memory: 55Mi
      cpu: 50m

webhook:
  resources:
    limits:
      memory: 50Mi
      cpu: 500m
    requests:
      memory: 25Mi
      cpu: 50m

resources:
  limits:
    memory: 80Mi
    cpu: 500m
  requests:
    memory: 40Mi
    cpu: 50m
</#if>