apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: ${namePrefix}argocd
  annotations:
<#if mail.active?? && mail.active>
    notifications.argoproj.io/subscribe.email: ${argocd.emailToAdmin}
</#if>
spec:
  description: AppProject for ArgoCD-specific applications.
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  # must be able to get all git repos because of the Applications pointing to other repos
  sourceRepos:
    - '*'
  # Allow applications from all namespaces to use this project for now.
  sourceNamespaces:
    - '*'
