apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-resources
  # In a real-world scenario these might to into a separate namespace
  namespace: ${namePrefix}argocd
  annotations:
<#if mail.active??>
    notifications.argoproj.io/subscribe.email: ${argocd.emailToAdmin}
</#if>
spec:
  description: Contains basic cluster-resources
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
  - ${scmm.baseUrl}/repo/${namePrefix}argocd/cluster-resources
  - https://codecentric.github.io/helm-charts
  - https://charts.external-secrets.io
  - https://helm.releases.hashicorp.com
  - https://kubernetes.github.io/ingress-nginx
<#if mirrorRepos>
  - ${scmm.baseUrl}/repo/3rd-party-dependencies/kube-prometheus-stack
<#else>
  - https://prometheus-community.github.io/helm-charts
</#if>

  # allow to only see application resources from the specified namespace
  sourceNamespaces:
    - '${namePrefix}argocd'

  # Allow all namespaced-scoped resources to be created
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  # Allow all cluster-scoped resources to be created
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
