apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example-apps
  namespace: ${config.application.namePrefix}argocd
  annotations:
<#if config.features.mail.active?? && config.features.mail.active>
     notifications.argoproj.io/subscribe.email: ${config.features.argocd.emailToUser}
</#if>
spec:
  description: Contains examples of end-user applications
  destinations:
  - namespace: ${config.application.namePrefix}example-apps-production
    server: https://kubernetes.default.svc
  - namespace: ${config.application.namePrefix}example-apps-staging
    server: https://kubernetes.default.svc
  sourceRepos:
  - ${scmm.repoUrl}argocd/example-apps.git
  - ${scmm.repoUrl}argocd/nginx-helm-umbrella.git
  
  
  # allow to only see application resources from the specified namespace
  sourceNamespaces:
    - '${config.application.namePrefix}example-apps-staging'
    - '${config.application.namePrefix}example-apps-production'
    <#if config.features.argocd.operator>
    - '${config.application.namePrefix}argocd'
    </#if>


  # Allow all namespaced-scoped resources to be created
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Deny all cluster-scoped resources from being created. Least privilege.
  clusterResourceWhitelist: