apiVersion: v1
kind: ServiceAccount
metadata:
  name: gop-sa
  namespace: gop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gop-sa-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: gop-sa
    namespace: gop
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
