apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-argocd
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/mgmt/multi-tenant-cluster-resources.git
        revision: main
        directories:
          - path: tenants/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: argocd
      source:
        repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/mgmt/multi-tenant-cluster-resources.git
        targetRevision: main
        path: '{{ .path.path }}/argocd/projects'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd-{{.path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true