apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns3
---
apiVersion: v1
kind: Namespace
metadata:
  name: gop-mgmt
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demoapplication
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: ns1
            appRepo: "http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/example-apps"
            cluster: in-cluster
            folder: apps/spring-petclinic-helm/staging
          - namespace: ns2
            appRepo: "http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/example-apps"
            cluster: in-cluster
            folder: apps/spring-petclinic-helm/production
          - namespace: ns3
            appRepo: "http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/example-apps"
            cluster: in-cluster
            folder: apps/spring-petclinic-helm/qs
  template:
    metadata:
      name: "my-app-{{namespace}}"
    spec:
      project: argocd
      source:
        path: "{{folder}}"
        repoURL: "{{appRepo}}"
        targetRevision: main
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      info:
        - name: "Application Repository"
          value: "{{appRepo}}" # Store app-specific repo as metadata
      ignoreDifferences:
      - group: ""
        kind: Application
        jsonPointers:
          - /metadata/annotations/argocd.argoproj.io~1instance