apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-helm-jenkins
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    # Name of secret to be created
    name: nginx-helm-jenkins
  data:
    - secretKey: some-secret # Key within target secret
      remoteRef:
        key: secret/staging/nginx-helm-jenkins
        property: example
