apiVersion: v1
kind: Pod
metadata:
  name: tmp-docker-gid-grepper
spec:
  containers:
    - args:
        - sleep
        - "Infinity"
      # Note: When upgrading, use same image as in initContainer create-agent-working-dir (values.yaml) for performance reasons
      image: bash:5-alpine3.19
      name: tmp-docker-gid-grepper
      volumeMounts:
        - name: group
          mountPath: /etc/group
          readOnly: true
  nodeSelector:
    node: jenkins
  volumes:
    - name: group
      hostPath:
        path: /etc/group
