#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

serviceName="$1"
namespace="$2"
ip=$(kubectl -n "${namespace}" get svc "${serviceName}" --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")

if [[ -z "${ip}" ]]; then
  echo "Service '${serviceName}' in namespace '${namespace}' does not have an external ip (yet)" 1>&2
  exit 1;
else
  echo http://${ip}
fi