#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

BASEDIR=$(dirname $0)
ABSOLUTE_BASEDIR="$(cd ${BASEDIR} && pwd)"

# Allow for running this script directly via curl without redundant code 
if [[ -f ${ABSOLUTE_BASEDIR}/utils.sh ]]; then
  source ${ABSOLUTE_BASEDIR}/utils.sh
else
  source <(curl -s https://raw.githubusercontent.com/cloudogu/gitops-playground/main/scripts/utils.sh)
fi

serviceName="$1"
namespace="$2"
ip=$(getExternalIP "${serviceName}" "${namespace}")

if [[ -z "${ip}" ]]; then
  echo "Service '${serviceName}' in namespace '${namespace}' does not have an external ip (yet)" 1>&2
  exit 1;
else
  echo http://${ip}
fi