#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

function getExternalIP() {
  local serviceName="$1"
  local namespace="$2"
  local externalIp=""

  while [[ -z "${externalIp}" ]]; do
    externalIp=$(kubectl -n "${namespace}" get svc "${serviceName}" -o=jsonpath="{.status.loadBalancer.ingress[0]['hostname','ip']}")
    [[ -z "${externalIp}" ]] && sleep 10
  done
  echo "${externalIp}"
}

serviceName="$1"
namespace="$2"
ip=$(getExternalIP "${serviceName}" "${namespace}")

if [[ -z "${ip}" ]]; then
  echo "Service '${serviceName}' in namespace '${namespace}' does not have an external ip (yet)" 1>&2
  exit 1;
else
  echo http://${ip}
fi
