content:
  repos:
    - url: https://github.com/cloudogu/gitops-playground
      path: examples/init-multi-tenancy/
      ref: main
      templating: true
      type: FOLDER_BASED
      overwriteMode: UPGRADE

  namespaces:
    - tenant-argocd
  variables:
