apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-umbrella
  namespace: ${config.application.namePrefix}argocd
spec:
  destination:
    namespace: ${config.application.namePrefix}example-apps-production
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/nginx-helm-umbrella
    repoURL: ${scm.repoUrl}argocd/example-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true