apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault-reader
  namespace: ${namePrefix}example-apps-production
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: ${namePrefix}example-apps-production
spec:
  provider:
    vault:
      server: "http://vault.${namePrefix}secrets.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "production"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "external-secrets-vault-reader"
