#!/bin/bash

# OUTPUTFILE="./docs/out.md"
# START_MARKER="<!-- GENERATED BY SCRIPT -->"
# END_MARKER="<!-- END GENERATED CONTENT -->"
#
# NEW_CONTENT=$(echo "new content here")
#
# if [ ! -f "$FILE" ]; then
#     echo "Fehler: $FILE nicht gefunden."
#     exit 1
# fi
#
# sed -e "/$START_MARKER/,/$END_MARKER/c\\" -e "$START_MARKER\n$NEW_CONTENT\n$END_MARKER" "$OUTPUTFILE" > "${OUTPUTFILE}.tmp" && mv "${OUTPUTFILE}.tmp" "$OUTPUTFILE"
#
# echo "Bereich in $OUTPUTFILE wurde erfolgreich aktualisiert."

GROOVY_CONTENT=$(cat ./src/main/groovy/com/cloudogu/gitops/config/Config.groovy)
DESC_SOURCE="./src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy"
SCHEMA_FILE=./docs/configuration.schema.json
OUTPUT_FILE=./out.md

# check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "Error: 'jq' is not installed or not in \$PATH."
    exit 1
fi

echo "# Overview of all config options" > $OUTPUT_FILE
echo "Here you can find all config keys, their default value an a description\n" >> $OUTPUT_FILE


write_table() {
    local json_path_array=$1
    local prefix=$2

    echo "| Option | Description | Type | Default |" >> "$OUTPUT_FILE"
    echo "| :--- | :--- | :--- | :--- |" >> "$OUTPUT_FILE"

    # jq Logik:
    # 1. Pfade finden, die eine Beschreibung oder einen Typ haben (nur bei Objekten prüfen!)
    # 2. Pfad-Segmente wie 'properties' oder 'oneOf' entfernen
    # 3. Aufeinanderfolgende Duplikate im Pfad löschen (url.url -> url)
    jq -r --argjson path "$json_path_array" --arg pref "$prefix" '
        def to_s:
            if type == "array" then join(", ")
            elif type == "null" then "-"
            else tostring end;

        # Bereinigt den Pfad von Schema-Keywords und Duplikaten
        def clean_path(p):
            [ p[] | select(tostring | test("properties|oneOf|anyOf|allOf|items|^[0-9]+$") | not) ]
            | reduce .[] as $item ([]; if .[-1] == $item then . else . + [$item] end);

        getpath($path) |
        [
            # Wir suchen Pfade zu Objekten, die description oder type haben
            paths(if type == "object" then has("description") or has("type") else false end) as $p
            | $p as $base_path
            | getpath($base_path) as $node

            # Nur echte Endknoten (keine reinen Container-Objekte mit Properties)
            | select($node.type != "object" or ($node.properties == null and $node.oneOf == null))

            | (clean_path($base_path)) as $parts
            | ($pref + (if ($parts | length) > 0 then "." + ($parts | join(".")) else "" end)) as $full_name

            | {
                name: ("`" + $full_name + "`"),
                desc: (($node.description // "-") | gsub("\n"; " ")),
                type: ($node.type | to_s),
                default: ("`" + ($node.default | to_s) + "`")
            }
        ]
        | unique_by(.name) | .[]
        | "| \(.name) | \(.desc) | \(.type) | \(.default) |"
    ' "$SCHEMA_FILE" >> "$OUTPUT_FILE"

    echo "" >> "$OUTPUT_FILE"
}

# --- Teil 1: Globale Keys ---
echo "parsing global config keys..."
KEYS=$(jq -r '.properties | keys[] | select(. != "features" and . != "stages")' "$SCHEMA_FILE")

for KEY in $KEYS; do
    echo "  -> $KEY"
    echo "## ${KEY^}" >> "$OUTPUT_FILE"
    write_table "[\"properties\", \"$KEY\"]" "$KEY"
done

# --- Teil 2: Features ---
echo "parsing feature config keys..."
echo "## Features" >> "$OUTPUT_FILE"
echo -e "Configuration of features supported by gitops-playground.\n" >> "$OUTPUT_FILE"

FEATURE_KEYS=$(jq -r '.properties.features.properties | keys[]' "$SCHEMA_FILE")

for SUBKEY in $FEATURE_KEYS; do
    echo "  -> features.$SUBKEY"
    echo "### Feature: ${SUBKEY^}" >> "$OUTPUT_FILE"
    write_table "[\"properties\", \"features\", \"properties\", \"$SUBKEY\"]" "features.$SUBKEY"
done

echo "Done!"
