apiVersion: v1
kind: Secret
metadata:
  name: jenkins-credentials
  namespace: gop-job
type: Opaque
stringData:
  username: admin
  password: this_is_for_your_ads
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-credentials
  namespace: gop-job
type: Opaque
stringData:
  username: admin
  password: who_can_read_this
---
