features:
  argocd:
  # monitoring:
  #   active: true
  #   helm:
  #     grafanaImage: "172.18.0.2:30002/library/grafana:latest"
  #     grafanaSidecarImage: "172.18.0.2:30002/library/k8s-sidecar:latest"
  #     prometheusImage: "172.18.0.2:30002/library/prometheus:latest"
  #     prometheusOperatorImage: "172.18.0.2:30002/library/prometheus-operator:latest"
  #     prometheusConfigReloaderImage: "172.18.0.2:30002/library/prometheus-config-reloader:latest"
  # secrets:
  #   externalSecrets:
  #     helm:
  #       image: "172.18.0.2:30002/library/external-secrets:latest"
  #   vault:
  #     helm:
  #       image: "172.18.0.2:30002/library/vault:latest"
  certManager:
    active: true
    helm:
      image: "airgappedreg/library/cert-manager-controller:latest"
      webhookImage: "airgappedreg/library/cert-manager-webhook:latest"
      cainjectorImage: "airgappedreg/library/cert-manager-cainjector:latest"
