apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-argocd-access-mailhog
  namespace: config.application.namePrefix.monitoring
spec:
  podSelector:
      matchLabels:
        app.kubernetes.io/name: mailhog
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: config.application.namePrefix.argocd
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-notifications-controller
      ports:
        - protocol: TCP
          port: 1025
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-argocd-access-scmm
  namespace: config.application.namePrefix.scm-manager
spec:
  podSelector:
    matchLabels:
      app: scm-manager
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: config.application.namePrefix.argocd
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-repo-server
      ports:
        - protocol: TCP
          port: 8080
---