apiVersion: v1
kind: Secret
metadata:
  name: gop-config
  namespace: gop-mgmt
type: Opaque
data:
  config.yaml: Y29uZmlnOgogIHNldHRpbmcxOiB2YWx1ZTEKICBzZXR0aW5nMjogdmFsdWUyCiAgc2V0dGluZzM6CiAgICBzdWJzZXR0aW5nMTogc3VidlZhbHVlMQogICAgc3VibWV0dGluZzI6IHN1YnZhbHVlMg==